### ISSUE TITLE
Column specifications and content

### ISSUE THREAD

**Issue by TCLamnidis** [poseidon-framework/poseidon-framework.github.io#10]
Concerning https://github.com/poseidon-framework/poseidon2-schema/blob/master/janno_columns.tsv

**1.  Publication Status**

Publication_Status | bibtex key (e.g. "@AuthorJournalYear") or "unpublished"
-- | --

It seems that if the Publication status actually starts with an `@`, either the bibtex validator doesn't accept the key containing the character, or the poseidon validator prints the following error:
```
! The .bib file does not contain the literature in the janno file or the bibtex keys are different
! This seems to be a valid package, but some things are fishy.
```
Removing the `@` from the `.janno` file fixed the issue, but it seems like an update is needed, either to the validator (strip leading `@`) or to the content explanation for the field.

**2. mtContamination error**

mtContam_stderr | Standard error of ContamMix/Schmutzi estimate
-- | --

ContamMix doesn't actually return a stderr, but a 95% confidence interval instead, making the error around the mode asymmetric. In my own package I have reported the largest difference between MAP and the edges of the 95% confidence interval, but that can be somewhat misleading. It would be good to either allow people to specify mtDNA contamination error as an interval or two fields with min and max of the CI (which can be done for both stderr and 95%CI), or give clear instructions on how one should report a 95%CI here.

**Comment by nevrome** [comment]
As both @stschiff and @wolfgangaroo are leaning towards a solution that involves no changes to the standard, but only to the documentation, I moved it here into the homepage repository.
