### ISSUE TITLE
Nit: Maybe use example domains for documentation purposes

### ISSUE THREAD

**Issue by xrotwang** [poseidon-framework/poseidon-framework.github.io#12]
Currently, in [standard.md](https://github.com/poseidon-framework/poseidon-framework.github.io/blob/master/standard.md) email addresses in domains `institute.org`, etc are used. There's a couple of [special domains](https://en.wikipedia.org/wiki/Example.com), designed explicitly for this purpose. That's not too much of an issue here, but one may still inadvertently expose actual people to getting spammed.

**Comment by stschiff** [comment]
Good points. Thanks. Will fix that.
