### ISSUE TITLE
Make persistent url at https://w3id.org

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-framework.github.io#2]
For linked data, we need to have a persistent URL to host our `terms.rdf` and various schema definitions. For this reason I have provisionally assumed in all schema definitions so far that we'll eventually have such a persistent URL at `https://w3id.org/poseidon`. This seems to be easy to set up, following the instructions on `https://w3id.org`, with a redirect on our GitHub page. Later, if we decide to move away from github, perhaps to an MPI-hosted website, we can just change the redirect with w3id.org and don't have to change any of the linked data RDF terms.

So we need to grab `https://w3id.org/poseidon` and set up that redirect.

**Comment by stschiff** [comment]
OK, I had a look into [https://w3id.org](https://w3id.org) and it's pretty straight forward to set up a redirect, but it requires writing an `.htaccess` file. Does anyone have experience with that?

**Comment by maxibor** [comment]
According to [this](https://mediatemple.net/community/products/dv/204643270/using-htaccess-rewrite-rules), it should be as simple as having this `.htacess` file here [https://github.com/perma-id/w3id.org/blob/master/poseidon/.htaccess](https://github.com/perma-id/w3id.org/blob/master/poseidon/.htaccess). 

```bash
Options +FollowSymLinks
RewriteEngine on
RewriteRule ^$ https://poseidon-framework.github.io [R=302,L]
```

See example [here](https://github.com/perma-id/w3id.org/tree/master/EXACT)

**Comment by stschiff** [comment]
But do you understand what all of this means and does? Say, the `[R=302,L]` clutter?

**Comment by maxibor** [comment]
`302` is the type of redirection (see [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections), L is for telling Apache to stop looking any further ([httpd.apache.org/docs/2.4/rewrite/flags.html](https://httpd.apache.org/docs/2.4/rewrite/flags.html))

**Comment by maxibor** [comment]
A lot more example [here](https://gist.github.com/ScottPhillips/1721489)

**Comment by maxibor** [comment]
I opened the PR [here](https://github.com/perma-id/w3id.org/pull/1710)

**Comment by stschiff** [comment]
Woohoo, it works. We can now access our terms and schema files like this `http://w3id.org/poseidon/terms.rdf.json` or `http://w3id.org/poseidon/sitesTable-schema.json`.

Thanks a lot. That's done.
