### ISSUE TITLE
flag "--onlyGeno" not further described

### ISSUE THREAD

**Issue by llacher** [poseidon-framework/poseidon-framework.github.io#36]
On the webpage, the description of the forge-command use is missing an explanation on what the --onlyGeno flag would do.

**Comment by stschiff** [comment]
Hmm. True, but on the other hand, that option does show up in the help output of the command, which is also shown in the documentation page (at least it can be opened from a little arrow). I have just committed a little change into master that gives an explanation in the bottom of the forge command section in the newest trident doc. It doesn't load for me right now, so I can't confirm it's there on the site, but it's in the source code. So let's close this issue once someone has seen it live.
