### ISSUE TITLE
Get terms.rdf.json to be statically hosted

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-framework.github.io#4]
We need to statically serve the file `terms.rdf.json` (which gets automatically copied here from Poseidon-schema (see [Issue #3 in that repo](https://github.com/poseidon-framework/poseidon-schema/issues/3#issuecomment-597600600)). I think just `https://poseidon-framework.github.io/terms.rdf.json` as URL would be good. 

We can set up the redirect from `w3id.org/poseidon` (yet to be registered)

There will be more files to come. The schema files need to be also copied and statically served, so perhaps we should have a sub-dir called `static_schema_files` or something prettier?

**Comment by nevrome** [comment]
https://poseidon-framework.github.io/terms.rdf.json already works....

**Comment by stschiff** [comment]
Oh wow... look at that. Great! OK, I guess we can already close this then. We'll just have those files in the root... why not.

One thing I just realised is that the nice Firefox rendering of rdf files doesn't work for jsonld files. So it might be good to translate the jsonld automatically to rdf (XML) before pushing it into this repo. I'll raise a separate issue for that.
