### ISSUE TITLE
Add a tutorial for a common workflow: A Western Eurasian PCA with projection

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-framework.github.io#40]
I was recently approached by @DivyaratanPopli on how to prepare a simple Western Eurasian PCA for the projection of ancient samples with the tools and data provided by and for Poseidon. This is a very common application and I suggest we add a tutorial for that on the website.

Maybe we elevate such tutorials, including the *Getting started* section, to an own top level category of the website.

**Comment by TCLamnidis** [comment]
Yes. My thought were more that there would be some training material for poseidon and we would simply port over some of it for the uses of any future HAAM summer school.
