### ISSUE TITLE
Update URL to www.poseidon-adna.org?

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-framework.github.io#42]
We could change the URL for our website to 

www.poseidon-adna.org

Described here:
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site

What is unclear to me is whether the old URL will then still work but automatically redirect. That would be good. If it stops working it would be bad.

**Comment by nevrome** [comment]
I think it continues to work. Check out this random example: https://github.com/nickneos/nickneos.github.io

https://nickneos.github.io and https://www.nickneos.com both point to the same homepage.

**Comment by stschiff** [comment]
Done!
