### ISSUE TITLE
Move documentation from READMEs into this repository

### ISSUE THREAD

**Issue by stschiff** [poseidon-framework/poseidon-framework.github.io#6]
I think embedding the existing READMEs for trident, the standard, and so forth, was very clever, and it certainly has the advantage that we can keep the documentations for trident, standard and PoseidonR in their respective packages. At least for trident and the standard, however, I somehow feel it also hampers flexibility to maintain and develop this webpage further. For example, it could make sense to weave the individual docs more together to create a comprehensive overview or getting started page, or to document the server API together with trident, or such things.

I would suggest to move the individual documentations here directly into this website-repository, and replace the original READMEs with some basic info and then a link to this webpage. This would allow us to freely design this webpage to be maximally user-friendly and engaging, without the danger to compartmentalise the docs for the individual parts.

(Note that copying the READMEs over here with a gh-action won't help, I think, as it still would mean that we are forced to keep the documentations as separate chapters.)

**Comment by nevrome** [comment]
Alright - sounds good to me! :+1:

**Comment by stschiff** [comment]
OK, I'll make this change

**Comment by stschiff** [comment]
Done.

**Comment by nevrome** [comment]
You also moved the schema and I'm not 100% sure about that. Having an own repo for that allowed us to make clear releases only for the core standard definition.

**Comment by stschiff** [comment]
I agree, but in my view those releases are independent from the documentation, aren't they?

**Comment by nevrome** [comment]
Well - https://github.com/poseidon-framework/poseidon2-schema/blob/master/README.md was the definition, not the documentation.

**Comment by stschiff** [comment]
OK, got it. In that case I'll move it back here, but then I would like to avoid duplication and then list on the website only a high-level summary of the different components, and then referring to this README as the main standard. I'll think of something and make a proposal. Easy to revert and change again.
